language: python

cache: pip

dist: trusty

python:
  - '2.7'

services:
  - mysql

branches:
  only:
  - master
  - develop

before_install:
  - mysql -e 'CREATE DATABASE sarai_maps_test_db;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('password') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mkdir data
  - mkdir data/cache
  - cp conf/main.ci.yml conf/main.yml

install: "pip install -r requirements.txt"

script:
 - python -m unittest discover

notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

  slack:
    secure: DGlDsBIs9HHQ3AXAtuHlclWk9IhLQ3BKn7XNJgOm1mfWe8Eikgv4pboX0xXU4vgdPt49/XtczJXJaTX9uEKQIsFpXOcNFVqZV9c6i6UNAphsKItSsAGFSuk9kuVo/JxrHqhvC3YTADnoPk9OS2yuW3331FmSgWDRekZBGZyDH6KW2+NhnvNq2TAOXn/uS1Lc5vWeXc12zYEoNApS6POt5KKytSeTK2n1EE54X+Yky2MtWF0VbGM/5d4ymMM2DmspJyaK6CW/nseIT/ZlFc6Vmn1xLusYdDOwLTN8dvK/RDW9EJghw2tiIvdoO6lrKUykEvRuygJbGNhQbdr6/ZsQq9XW5m5ietJHxqIJWqcT+M6vLoc4WnuSTbNjW8jv3Y7nLqg6irPW273KspUDzpgrkMZfYw8AI0T2hWwSfihMp7p5TAWMw4REZRWVGAh2fmwBTz45dZb69rHz71WkCj/E9LLh5pByAD63ExjAlEuMwxX9iWeRSt7j42j7ugMFIrmSIJUiLM1igqUnMOHcDUu4uz665Uo880p9T14jPouwQeU0hhtuKXbnPtEWuZ0rVy0C6721QljRVn/Gl8PzcjX5KMVyTfxj29lDizjXqBua+OUr9REQMUrh3vz+FnlbN09xaS2iZtEdyAK5G+3dr7aSuObyAsjNeKAsMDAq45UIw2k=


